name: .NET

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: 
      - "**"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build Helper Service
      run: dotnet build HelperService/HelperService.csproj
    - name: Build Cs4rsaDatabaseService
      run: dotnet build Cs4rsaDatabaseService/Cs4rsaDatabaseService.csproj
    - name: Build TeacherCrawlerService1
      run: dotnet build TeacherCrawlerService1/TeacherCrawlerService1.csproj
    - name: Build SubjectCrawlService1
      run: dotnet build SubjectCrawlService1/SubjectCrawlService1.csproj
    - name: Build StudentCrawlerService
      run: dotnet build StudentCrawlerService/StudentCrawlerService.csproj
    - name: Build CurriculumCrawlerService
      run: dotnet build CurriculumCrawlerService/CurriculumCrawlerService.csproj
    - name: Test Category=TestInLocal
      run: dotnet test --filter TestCategory=TestInLocal
