name: .NET

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: 
      - "**"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test Category=TestInLocal
      run: dotnet test --filter TestCategory=TestInLocal
